// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const SquareVerifier = artifacts.require('SquareVerifier');
const { proof, inputs } = require('./proof.json')

contract('SquareVerifier', accounts => {
  // Test verification with correct proof
  // - use the contents from proof.json generated from zokrates steps
  it('verifies with correct proof' , async () => {
    const contract = await SquareVerifier.new({ from: accounts[0] })
    assert.equal(await contract.verifyTx.call(proof.a, proof.b, proof.c, inputs), true)
  })

  // Test verification with incorrect proof
  it('does not verify with incorrect proof' , async () => {
    const contract = await SquareVerifier.new({ from: accounts[0] })
    // changed inputs[0] to 10
    inputs[0] = "0x000000000000000000000000000000000000000000000000000000000000000a"
    assert.equal(await contract.verifyTx.call(proof.a, proof.b, proof.c, inputs), false)
  })
})
