// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const SquareVerifier = artifacts.require('SquareVerifier');

contract('SquareVerifier', accounts => {
  // Test verification with correct proof
  // - use the contents from proof.json generated from zokrates steps
  it('verifies with correct proof' , async () => {
    const { proof, inputs } = require('./proof3.json')
    const contract = await SquareVerifier.new({ from: accounts[0] })
    assert.equal(await contract.verifyTx.call(proof.a, proof.b, proof.c, inputs), true)
  })

  it('verifies with correct proof for 4 * 4 = 16' , async () => {
    const { proof, inputs } = require('./proof4.json')
    const contract = await SquareVerifier.new({ from: accounts[0] })
    assert.equal(await contract.verifyTx.call(proof.a, proof.b, proof.c, inputs), true)
  })

  // Test verification with incorrect proof
  it('does not verify with incorrect proof' , async () => {
    const { proof, inputs } = require('./proof3.json')
    const contract = await SquareVerifier.new({ from: accounts[0] })
    // changed inputs[0] to 10
    inputs[0] = "0x000000000000000000000000000000000000000000000000000000000000000a"
    assert.equal(await contract.verifyTx.call(proof.a, proof.b, proof.c, inputs), false)
  })
})
